import { generatePath } from "react-router-dom";

export const PATHS = {
    admin: "/admin",
    home: "/",
    login: "/login",
    register: "/register",
    unauthorized: "/unauthorized",
    productList: "/products",
    product: "/product/:id",
    createProduct: "/createProduct",
    categoryTree: "/categoryTree",
    categoryAdmin: "/categoryAdmin",
    oauth2Callback: "/oauth2/callback",
    any: "*",
    profile: "/profile",
    verifyEmail: "/verifyEmail",
    verifyEmailToken: "/verify-email/:token",
    verify2fa: "/verify-2fa",
    brandCreate: "/brandCreate",
    forgotPassword: "/forgot-password",
    resetPassword: "/reset-password/:token",
    deleteAccount: "/delete-account",
    cart: "/cart",
    checkout: "/checkout",
    orderConfirmation: "/order/:orderId/confirmation",
    orders: "/orders",
    order: "/order/:orderId"
};

export const paths = {
    admin: () => PATHS.admin,
    home: () => PATHS.home,
    login: () => PATHS.login,
    register: () => PATHS.register,
    unauthorized: () => PATHS.unauthorized,
    productList: () => PATHS.productList,
    product: (id) => generatePath(PATHS.product, {id}),
    createProduct: () => PATHS.createProduct,
    categoryTree: () => PATHS.categoryTree,
    categoryAdmin: () => PATHS.categoryAdmin,
    oauth2Callback: () => PATHS.oauth2Callback,
    profile: () => PATHS.profile,
    verifyEmail: () => PATHS.verifyEmail,
    verifyEmailToken: (token) => generatePath(PATHS.verifyEmailToken, {token}),
    verify2fa: () => PATHS.verify2fa,
    brandCreate: () => PATHS.brandCreate,
    forgotPassword: () => PATHS.forgotPassword,
    resetPassword: (token) => generatePath(PATHS.resetPassword, {token}),
    deleteAccount: () => PATHS.deleteAccount,
    cart: () => PATHS.cart,
    checkout: () => PATHS.checkout,
    orderConfirmation: (orderId) => generatePath(PATHS.orderConfirmation, {orderId}),
    orders: () => PATHS.orders,
    order: (orderId) => generatePath(PATHS.order, {orderId}),
}